Pull request 02102023
FPTU-GHub-Capstone/game-management-service pull request #1
Opened 2023-10-02 14:25 UTC by AnhQuoc2906

2023-10-02 16:28 UTC, danielNg91 requested changes

2023-10-02 16:28 UTC, danielNg91 commented on Api/Controllers/RestAPI/UserController.cs
> +        public IEnumerable<string> Get()
asp.net have problem when 2 controller have methods that the same name, Give methods in this class a more specific name

2023-10-02 16:28 UTC, danielNg91 commented on Api/Controllers/RestAPI/UserController.cs
> +        [Route("Client")]
remove these clients api

2023-10-02 16:28 UTC, danielNg91 commented on Api/Controllers/RestAPI/UserController.cs
> +            try
remove this try catch when you just use it for error handling

2023-10-02 16:28 UTC, danielNg91 commented on Application/Interfaces/ICharacterServices.cs
> +    Task<CharacterAsset> GetCharacterAsset(Guid characterAssetId);
fix same as above

2023-10-02 16:28 UTC, danielNg91 commented on Application/Interfaces/IGameServices.cs
> +    Task<ICollection<GameEntity>> GetGames();
fix same as above

2023-10-02 16:28 UTC, danielNg91 commented on Application/Interfaces/ITransactionServices.cs
> +    Task<ICollection<TransactionEntity>> GetTransactions();
fix same as above

2023-10-02 16:28 UTC, danielNg91 commented on Application/Interfaces/IUserServices.cs
> +    Task<ICollection<Client>> GetClients();
fix same as above, remove services for client

2023-10-02 16:28 UTC, danielNg91 commented on Application/Services/ActivityServices/ActivityServices.cs
> +    public async Task<ICollection<ActivityEntity>> GetActivities() {
this one line function is not necessary

2023-10-02 16:28 UTC, danielNg91 commented on Application/Services/ActivityServices/ActivityServices.cs
> +        var activities = await _activityRepo.ListAsync();
useless oneline function, remove it otherswhere

2023-10-02 16:28 UTC, danielNg91 commented on Application/Services/ActivityServices/ActivityServices.cs
> +    public async Task<ICollection<ActivityType>> GetActivityTypes(Guid id, int typeId)
What is this function used for?

2023-10-02 16:28 UTC, danielNg91 commented on Application/Services/CharacterServices/CharacterServices.cs
> +        var charAss = await _characterAssetRepo.ListAsync();
we already have SumAsync function in Repository, why we need this implementation?

2023-10-02 16:36 UTC, danielNg91 requested changes

2023-10-02 16:36 UTC, danielNg91 commented on Domain/Entities/Activity/ActivityEntity.cs
> +
remove this line break

2023-10-02 16:36 UTC, danielNg91 commented on Infrastructure/Contexts/EntityTypeConfigurations/EntityTypeConfiguration.cs
> +public class EntityTypeConfiguration :
split to smaller files, just 1 class for 1 EntityTypeConfiguration (if needed)

2023-10-03 01:59 UTC, AnhQuoc2906 commented on Api/Controllers/RestAPI/ActivityController.cs
> +                throw new Exception("0 item in list");
Remove if-else, return collection:

```
public async Task<IActionResult> GetActivitíes()
        {
            var activities = await _activityServices.GetActivities();
            return Ok(activities);
        }
```

2023-10-03 02:39 UTC, AnhQuoc2906 commented on Api/Controllers/RestAPI/AttributeController.cs
> +                throw new Exception("0 item in list");
Remove if-else, return collection:

```
public async Task<IActionResult> Get()
        {
            var attribute = await _attributeServices.GetAttributeGroups();
            return Ok(attribute);
        }
```

2023-10-03 02:43 UTC, danielNg91 commented on Api/Controllers/RestAPI/ActivityController.cs
> +                throw new Exception("0 item in list");
yup, let return collection

2023-10-03 03:16 UTC, AnhQuoc2906 commented on Api/Controllers/RestAPI/AttributeController.cs
> +                attributeGroup.isDeleted = false;
Set abstract class to auto-generate like this:
```
public abstract class BaseEntity
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public bool isDeleted { get; set; } = false; //false: not deleted, true: deleted
    }
```

And change the post method to this: 

```
var attGrps = _attributeServices.GetAttributeGroups();
                foreach(var attgrp in attGrps.Result)
                {
                    if(attgrp.Name == attributeGroup.Name)
                    {
                        return Conflict(attgrp);
                    } else
                    continue;
                }
                var attGrp = new AttributeGroup
                {
                    Name = attributeGroup.Name,
                    Effect = attributeGroup.Effect
                };
                await _attributeServices.CreateAttributeGroup(attGrp);
                return NoContent();
    
    
```

2023-10-03 03:19 UTC, AnhQuoc2906 commented on Api/Program.cs
> +//Add configurations to Services
Change from comments to region like this
```
#region Add configurations to Services
var services = builder.Services;
services.AddAppServices();
#endregion
```

2023-10-03 03:22 UTC, AnhQuoc2906 commented on Domain/Entities/Activity/ActivityEntity.cs
> +
Fixed: 

```
public int Status { get; set; }
    // 1 Activity Type - M Activity
    public Guid ActivityTypeId { get; set; }
```

2023-10-03 16:16 UTC, danielNg91 requested changes

2023-10-03 16:16 UTC, danielNg91 commented on Api/Configurations/AppConfigurationService.cs
> +            services.AddScoped(typeof(IGenericRepository<>), typeof(GenericRepository<>));
gud cho'p

2023-10-03 16:16 UTC, danielNg91 commented on Api/Controllers/ActivityController.cs
> +    [AllowAnonymous]
remove it, we don't use auths in this services

2023-10-03 16:16 UTC, danielNg91 commented on Api/Controllers/ActivityController.cs
> +        public string Get(int id)
more specific name for this method. Don't use just Get, Post for controllers  methods

2023-10-03 16:16 UTC, danielNg91 commented on Api/Program.cs
> +builder.Services.AddDbContext<ApplicationDbContext>
map to configuration

2023-10-03 16:16 UTC, danielNg91 commented on Application/Interfaces/Activity/IActivityServices.cs
> +    Task<ActivityEntity> GetById(Guid activityId); // Get by Activity Id
what're these comments for?

2023-10-03 16:16 UTC, danielNg91 commented on Application/Interfaces/Activity/IActivityServices.cs
> +    Task<ICollection<ActivityEntity>> GetByTypeId(Guid activityTypeId); // Get by Activity Type Id
how about using overload for 2 methods?

2023-10-03 16:16 UTC, danielNg91 commented on Application/Services/ActivityServices/ActivityTypeServices.cs
> +            throw new Exception($"Activity type not found");
fixed by yesterday's comment

2023-10-03 16:16 UTC, danielNg91 commented on Application/Services/AssetServices/AssetAttributeServices.cs
> +    { // typeId: 1: AssetId, 2: AttributeGroupId
why still use typeId??

2023-10-04 04:43 UTC, danielNg91 requested changes

2023-10-04 04:43 UTC, danielNg91 commented on Api/Configurations/AppConfigurationService.cs
> +            services.AddDbContext<ApplicationDbContext>
map from appsettings.json to C# class

2023-10-04 04:43 UTC, danielNg91 commented on Application/Services/AttributeServices/AttributeServices.cs
> +            else continue;
this is end of for block, what is 'continue' use for?

2023-10-04 04:43 UTC, danielNg91 commented on Application/Services/AttributeServices/AttributeServices.cs
> +        if (check == false)
what you will do when check  == true?

2023-10-04 04:43 UTC, danielNg91 commented on Application/Services/WalletServices/WalletCategoryServices.cs
> +            throw new Exception($"Wallet category or game not found");
why you still throw an Exception. Should remember, Exception is the same as reponse with 500 status.

2023-10-04 16:07 UTC, closed without merging